Skip to content
You are on the latest version of DhanHQ API.
Ver 2.0 / API Documentation
Option Chain
Search

logoVer 2.0 / API Documentation
Introduction
Authentication
Trading APIs
Trading APIs
Orders
Super Order
Forever Order
Conditional Trigger
Portfolio and Positions
EDIS
Trader's Control
Funds & Margin
Statement
Postback
Live Order Update
Data APIs
Data APIs
Market Quote
Live Market Feed
Full Market Depth
Historical Data
Expired Options Data
Option Chain
Annexure
Instrument List
Releases
Table of contents
Option Chain
Expiry List
Option Chain
This API gives entire Option Chain of any Option Instrument, across exchanges and segments - for NSE, BSE and MCX traded options. With Option Chain, you get OI, greeks, volume, top bid/ask and price data of all strikes of a particular underlying.

POST	/optionchain	Get Option Chain of any instrument
POST	/optionchain/expirylist	Expiry List for Options of Underlying
Info

Rate limit for Option Chain API is set to one unique request every 3 seconds. This means you can fetch entire option chain for multiple different underlying instrument or multiple expiries of same instrument concurrently every 3 seconds.

Option Chain
Retrieve real-time Option Chain across exchanges for all underlying. You can fetch Open Interest (OI), Greeks, Volume, Last Traded Price, Best Bid/Ask and Implied Volatility (IV) across all strikes for any underlying.


curl --request POST \
--url https://api.dhan.co/v2/optionchain \
--header 'Content-Type: application/json' \
--header 'access-token: JWT' \
--header 'client-id: 1000000001' \
--data '{Request Body}'

Header

Header	Description
access-token
required	Access Token generated via Dhan
client-id
required	User specific identification generated by Dhan
Request Structure


{
    "UnderlyingScrip":13,
    "UnderlyingSeg":"IDX_I",
    "Expiry":"2024-10-31"
}

Parameters

Field	Field Type	Description
UnderlyingScri
required	int	Security ID of Underlying Instrument - can be found here
UnderlyingSeg	enum string	Exchange & segment of underlying for which data is to be fetched - here
Expiry	string	Expiry Date of Option, for which Option Chain is requested. List of active expiries can be fetched from here

Response Structure


{
"data": {
    "last_price": 25642.8,
    "oc": {
            "25650.000000": {
                "ce": {
                    "average_price": 146.99,
                    "greeks": {
                        "delta": 0.53871,
                        "theta": -15.1539,
                        "gamma": 0.00132,
                        "vega": 12.18593
                    },
                    "implied_volatility": 9.789193798280868,
                    "last_price": 134,
                    "oi": 3786445,
                    "previous_close_price": 244.85,
                    "previous_oi": 402220,
                    "previous_volume": 31931705,
                    "security_id": 42528,
                    "top_ask_price": 134,
                    "top_ask_quantity": 1365,
                    "top_bid_price": 133.55,
                    "top_bid_quantity": 1625,
                    "volume": 117567970
                },
                "pe": {
                    "average_price": 134.62,
                    "greeks": {
                        "delta": -0.46732,
                        "theta": -10.61131,
                        "gamma": 0.00109,
                        "vega": 12.2025
                    },
                    "implied_volatility": 11.939337251984934,
                    "last_price": 132.8,
                    "oi": 3096145,
                    "previous_close_price": 101.45,
                    "previous_oi": 2327260,
                    "previous_volume": 81224780,
                    "security_id": 42529,
                    "top_ask_price": 132.75,
                    "top_ask_quantity": 390,
                    "top_bid_price": 132.45,
                    "top_bid_quantity": 65,
                    "volume": 157009970
                }
            }
            .
            .
            .
        }
    },
    "status": "success"
}
Parameters

Field	Type	Description
data.last_price	float	LTP of the Underlying
data.oc	array	Option Chain Array - Strike Wise
data.oc.{strike}	array	Strike Price for Underlying
data.oc.{strike}.ce	array	Call Option data of particular strike
data.oc.{strike}.pe	array	Put Option data of particular strike
Call/Put Option Data

Field	Type	Description
average_price	float	Average Price of the Option Instrument for the day
greeks.delta	float	Measures the change of option's premium based on every 1 rupee change in underlying
greeks.theta	float	Measures measures how quickly an option's value decreases over time
greeks.gamma	float	Rate of change in an option's delta in relation to the price of the underlying asset
greeks.vega	float	Measures the change of option's premium in response to a 1% change in implied volatility
implied_volatility	float	Value of expected volatility of a stock over the life of the option
last_price	float	Last Traded Price of the Option Instrument
oi	int	Open Interest of the Option Instrument
previous_close_price	float	Previous day close price
previous_oi	int	Previous day Open Interest
previous_volume	int	Previous day volume
security_id	int	Security ID of the Option Instrument
top_ask_price	float	Current best ask price available
top_ask_quantity	int	Quantity available at current best ask price
top_bid_price	float	Current best bid price available
top_bid_quantity	int	Quantity available at current best bid price
volume	int	Day volume for Option Instrument
Expiry List
Retrieve dates of all expiries of any underlying, for which Options Instruments are active.


    curl --request POST \
    --url https://api.dhan.co/v2/optionchain/expirylist \
    --header 'Content-Type: application/json' \
    --header 'access-token: JWT' \
    --header 'client-id: 1000000001' \
    --data '{}'

Header

Header	Description
access-token
required	Access Token generated via Dhan
client-id
required	User specific identification generated by Dhan
Request Structure


    {
    "UnderlyingScrip":13,
    "UnderlyingSeg":"IDX_I"
    }

Parameters

Field	Field Type	Description
UnderlyingScri
required	int	Security ID of Underlying Instrument - can be found here
UnderlyingSeg	enum string	Exchange & segment of underlying for which data is to be fetched - here

Response Structure


{
    "data": [
        "2024-10-17",
        "2024-10-24",
        "2024-10-31",
        "2024-11-07",
        "2024-11-14",
        "2024-11-28",
        "2024-12-26",
        "2025-03-27",
        "2025-06-26",
        "2025-09-25",
        "2025-12-24",
        "2026-06-25",
        "2026-12-31",
        "2027-06-24",
        "2027-12-30",
        "2028-06-29",
        "2028-12-28",
        "2029-06-28"
    ],
    "status": "success"
}
Parameters

Field	Type	Description
data[]	array	All expiry dates of underlying in YYYY-MM-DD
Note

The rate limit applicable for Option Chain API is at 1 request per 3 second. This is because OI data gets updated slow, compared to LTP or other data parameter.


Note: For description of enum values, refer Annexure

Copyright © 2024 Moneylicious Securities Private Limited
HQ Bot
DhanHQ Chatbot
Power by

Show me how to place a buy order
How to get market data using Python?
How do i handle errors in Dhan APIs?
What are the authentication requirements?
March 18, 2026
HQ Bot
Hi! I'm your assistant. How can I help you today?

02:29 AM
Type your message...

Need Help?
