CLIENT_ID = "1106299230"
ACCESS_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJkaGFuIiwicGFydG5lcklkIjoiIiwiZXhwIjoxNzc0MjU4NjU5LCJpYXQiOjE3NzQxNzIyNTksInRva2VuQ29uc3VtZXJUeXBlIjoiU0VMRiIsIndlYmhvb2tVcmwiOiIiLCJkaGFuQ2xpZW50SWQiOiIxMTA2Mjk5MjMwIn0.k36X_laJIDQObTMOlEmPZtE8dN07rkNoxZ2iuJZ1maqKDVTcDtvipqOm8CfqEbbkOZcmWySL4NH0pCO-9SsgtQ"
